import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { portfolio } from './portfolio.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const papers = JSON.parse(readFileSync(path.join(root, 'data/publications.json'), 'utf8'));
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base = 'https://zi-hang-zhou.github.io';
const icons = {
  arrow: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
  sun: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg>',
  github: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19c-4 1-4-2-6-2m12 5v-4c0-1-.4-2-1-2 4-.5 7-2 7-6a5 5 0 0 0-1.5-3.5c.3-1 .2-2-.3-3.5 0 0-1.5-.5-4.2 1a14 14 0 0 0-6 0C6.3 2.5 4.8 3 4.8 3c-.5 1.5-.6 2.5-.3 3.5A5 5 0 0 0 3 10c0 4 3 5.5 7 6-.6.5-1 1.5-1 2v4"/></svg>'
};
const link = (url, text, cls='text-link') => `<a class="${cls}" href="${esc(url)}">${text}</a>`;
const tags = xs => `<div class="tags">${xs.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;

function paperCard(p, prefix) {
  const authors = p.authors.map(a=>a==='Zihang Zhou'?`<strong>${a}</strong>`:esc(a)).join(', ');
  const citation = `@article{zhou${p.year}${p.id.replaceAll('-','')},\n  title = {${p.title}},\n  author = {${p.authors.join(' and ')}},\n  journal = {arXiv preprint arXiv:${p.arxiv}},\n  year = {${p.year}},\n  doi = {10.48550/arXiv.${p.arxiv}}\n}`;
  return `<article class="paper-card" id="${p.id}" data-kind="${p.kind}">
    <figure class="paper-visual"><a href="${prefix}assets/${p.image}" class="figure-link" data-caption="${esc(p.figure)}" aria-label="Enlarge ${esc(p.short)} figure"><img src="${prefix}assets/${p.image}" alt="${esc(p.figure)}" loading="lazy" width="640" height="360"/><span class="zoom-hint">View figure ↗</span></a><figcaption>${esc(p.figure)} · <a href="https://arxiv.org/html/${p.version}">Source</a></figcaption></figure>
    <div class="paper-content"><div class="paper-meta"><span class="badge ${p.kind}">${esc(p.status)}</span>${p.firstAuthor?'<span class="badge first">First author</span>':''}<span class="year">${p.year}</span></div>
    <h3><a href="https://arxiv.org/abs/${p.arxiv}">${esc(p.title)}</a></h3>
    <details class="authors"><summary>${p.firstAuthor?'<strong>Zihang Zhou</strong> et al.':'Co-authored by <strong>Zihang Zhou</strong>'} <span>· ${p.authors.length} authors</span></summary><p>${authors}</p></details>
    <p class="paper-description">${esc(p.description)}</p>
    <div class="paper-links">${link(`https://arxiv.org/abs/${p.arxiv}`, 'Paper ↗')}${link(`https://arxiv.org/pdf/${p.arxiv}`, 'PDF ↗')}${p.code?link(p.code,'Code ↗'):''}${p.project?link(p.project,'Project ↗'):''}<button type="button" class="text-link cite-button" data-cite="cite-${p.id}" aria-expanded="false" aria-controls="cite-${p.id}">Cite</button></div>
    <div class="citation" id="cite-${p.id}" hidden><pre>${esc(citation)}</pre><button class="copy-citation" type="button">Copy BibTeX</button></div></div>
  </article>`;
}

function timeline() {
  return `<div class="timeline">
    <article><div class="timeline-date">JUN 2026 — PRESENT</div><div><h3>Microsoft Research Asia</h3><p class="role">Intern · Shanghai Office</p><p>Designing enterprise workflow tasks and evaluation datasets, and developing metrics and an evaluation framework for LLMs and agents.</p></div></article>
    <article><div class="timeline-date">APR — JUN 2026</div><div><h3>MAGIC · Shanghai Jiao Tong University</h3><p class="role">Undergraduate Researcher · Agentic Time Machine</p><p>Evaluated agents equipped with Time Machine infrastructure on future-event forecasting tasks.</p></div></article>
    <article><div class="timeline-date">OCT 2025 — APR 2026</div><div><h3>SJTU Data Analysis Study Group</h3><p class="role">Undergraduate Researcher · SetupX</p><p>Developed an autonomous repository-setup agent with retrieval-augmented experience reuse and refined its agent–environment interaction loop.</p></div></article>
    <article><div class="timeline-date">JUN — OCT 2025</div><div><h3>SJTU Data Analysis Study Group</h3><p class="role">Undergraduate Researcher · Data-Analyst Survey</p><p>Authored the video and 3D-model analysis sections and curated the accompanying research repository.</p></div></article>
  </div>`;
}

function education() {
  return `<div class="education-card"><span class="eyebrow">2024 — PRESENT</span><h3>Shanghai Jiao Tong University</h3><p>B.Eng. Candidate in Artificial Intelligence<br>School of Artificial Intelligence</p><p class="education-grades">GPA: 4.04 / 4.3 · Average score: 92.7</p><ul class="clean-list"><li><strong>National Scholarship</strong> · October 2025</li><li>Zhiyuan Honorary Scholarship</li><li>Admitted one year early through Gaokao, in Grade 11</li></ul></div>`;
}

function projectGrid(prefix) {
  const projects = [
    {name:'SetupX',category:'RESEARCH SYSTEM', image:'setupx.png',text:'From a repository URL to a verified environment. Experience retrieval, speculative execution, and adversarial verification.', url:'https://github.com/Zi-hang-Zhou/SetupX', tags:['LLM agents','Docker','XPU']},
    {name:'Workspace-Bench 1.0',category:'COLLABORATIVE RESEARCH',image:'workspace-bench.png',text:'A benchmark for agents working across realistic workspaces and large-scale file dependencies.',url:'https://github.com/OpenDataBox/Workspace-Bench',tags:['Evaluation','Workspace learning']},
    {name:'LLM/Agent-as-Data-Analyst',category:'SURVEY & RESEARCH RESOURCES',image:'data-analyst.png',text:'Research across data modalities, including my contributions on video and 3D-model analysis.',url:'https://github.com/weAIDB/awesome-data-llm',tags:['Multimodal AI','Data analysis']},
    {name:'SpeechMaster',category:'COURSE PROJECT',symbol:'↗',text:'Budget-aware self-supervised speech recognition with complementary model routing and representation-compression experiments.',url:'https://github.com/Zi-hang-Zhou/Speechmaster',tags:['Speech recognition','PyTorch']},
    {name:'KV Cache Compression',category:'COURSE PROJECT',symbol:'≋',text:'Comparing StreamingLLM, SnapKV, and PyramidKV on Pythia-70M: quality, memory, and latency trade-offs.',url:'https://github.com/Zi-hang-Zhou/NLP-project-work',tags:['LLM inference','Evaluation']},
    {name:'MS/MS Annotation Platform',category:'SCIENTIFIC TOOL',symbol:'⌁',text:'A local application for blind and model-assisted structure annotation, peak-level evidence, and exportable results.',url:'https://github.com/Zi-hang-Zhou/ms-ms-pred-annotations',tags:['Scientific AI','Annotation']}
  ];
  return `<div class="project-grid">${projects.map(p=>`<article class="project-card">${p.image?`<a class="project-image" href="${p.url}"><img src="${prefix}assets/${p.image}" alt="${esc(p.name)} overview from the paper" loading="lazy" width="600" height="320"></a>`:`<div class="project-symbol" aria-hidden="true">${p.symbol}</div>`}<div class="project-body"><span class="eyebrow">${p.category}</span><h3>${link(p.url,esc(p.name)+' ↗','')}</h3><p>${esc(p.text)}</p>${tags(p.tags)}</div></article>`).join('')}</div>`;
}

function shell(title, route, body) {
  const prefix = route==='/'?'./':'../';
  const nav = route === '/' && title === 'Home' ? [['#research','Projects'],['#experience','Experience'],['#about','About'],['/cv/','CV']] : [['/','Home'],['/publications/','Publications'],['/projects/','Projects'],['/cv/','CV']];
  const href = r => r.startsWith('#') ? r : r==='/'?prefix:prefix+r.slice(1);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="description" content="Zihang Zhou — AI undergraduate at Shanghai Jiao Tong University. Research on self-evolving LLM agents, evaluation, and reliable agentic systems."><meta name="theme-color" content="#faf8f4"><meta property="og:title" content="${esc(title)} · Zihang Zhou"><meta property="og:description" content="Research, publications, and projects in reliable and self-evolving LLM agents."><meta property="og:type" content="website"><meta property="og:url" content="${base}${route}"><meta property="og:image" content="${base}/assets/social.svg"><link rel="canonical" href="${base}${route}"><link rel="icon" href="${prefix}assets/favicon.svg" type="image/svg+xml"><title>${esc(title)} · Zihang Zhou</title><script src="${prefix}theme.js"></script><link rel="stylesheet" href="${prefix}styles.css"><script src="${prefix}app.js" defer></script></head>
<body class="${route==='/'?'home-page':'inner-page'}"><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="${prefix}" aria-label="Zihang Zhou home">Z<span>.</span></a><nav aria-label="Main navigation">${nav.map(([r,n])=>`<a href="${href(r)}"${r===route?' aria-current="page"':''}>${n}</a>`).join('')}</nav><div class="nav-tools"><a class="github-link" href="https://github.com/Zi-hang-Zhou" aria-label="GitHub profile">${icons.github}</a><button id="theme-toggle" class="icon-button" aria-label="Switch to dark theme" title="Switch theme" type="button">${icons.sun}</button></div></div></header>
<main id="main">${body}</main>
<footer class="site-footer"><p>© 2026 Zihang Zhou</p><div class="footer-links">${link('mailto:zzh2024@sjtu.edu.cn','Email')}${link('https://github.com/Zi-hang-Zhou','GitHub')}${link(prefix+'cv/Zihang-Zhou-CV.pdf','PDF CV')}${link(prefix+'credits/','Sources & credits')}</div></footer>
<dialog id="figure-dialog" aria-label="Expanded paper figure"><button class="dialog-close" type="button" aria-label="Close figure">×</button><img alt=""><p></p></dialog><div id="live-status" class="sr-only" role="status" aria-live="polite"></div></body></html>`;
}

const home = portfolio(papers, timeline);

const publications = `<section class="page-intro container"><span class="section-tag">Research</span><h1>Publications</h1><p>Papers on agent learning, verification, forecasting, and data analysis.</p></section><section class="container publication-section"><div class="filters" role="group" aria-label="Filter publications"><button type="button" data-filter="all" aria-pressed="true">All <span>4</span></button><button type="button" data-filter="accepted" aria-pressed="false">Accepted <span>1</span></button><button type="button" data-filter="preprint" aria-pressed="false">Preprints / under review <span>3</span></button></div><p class="quiet publication-note">Under-review manuscripts are listed separately from accepted publications. Expand an author line for the complete author list.</p><div class="paper-list">${papers.map(p=>paperCard(p,'../')).join('')}</div><p class="quiet sources-note">Bibliographic information and figures: arXiv. Venue and submission status: author-provided, September 2026. <a href="../credits/">Sources & credits</a>.</p></section>`;
const projects = `<section class="page-intro container"><span class="section-tag">Software</span><h1>Projects</h1><p>Research software, collaborative projects, and course experiments.</p></section><section class="container section-tight">${projectGrid('../')}</section>`;
const cv = `<section class="page-intro container cv-intro"><div><span class="eyebrow">CURRICULUM VITAE</span><h1>Zihang Zhou<span class="accent">.</span></h1><p>Artificial Intelligence · Shanghai Jiao Tong University</p></div>${link('./Zihang-Zhou-CV.pdf','Download PDF '+icons.arrow,'button primary')}</section><div class="container cv-layout"><aside class="cv-nav"><a href="#education">Education</a><a href="#experience">Experience</a><a href="#papers">Publications</a><a href="#skills">Skills</a><a href="#courses">Coursework</a></aside><div><section class="cv-section" id="education"><h2>Education & honors</h2>${education()}<p class="quiet">National Scholarship (top 0.5%, October 2025). Early admission through Gaokao: top 0.05% in Jiangsu Province. Figures supplied by the author.</p></section><section class="cv-section" id="experience"><h2>Research & internship experience</h2>${timeline()}</section><section class="cv-section" id="papers"><h2>Publications & preprints</h2><ol class="cv-papers">${papers.map(p=>`<li><a href="https://arxiv.org/abs/${p.arxiv}">${esc(p.title)}</a><p>${p.firstAuthor?'<strong>First author.</strong> ':''}${esc(p.status)}</p></li>`).join('')}</ol>${link('../publications/','Full author lists, figures & citations ↗')}</section><section class="cv-section" id="skills"><h2>Skills</h2><dl class="skills-list"><dt>Programming</dt><dd>Python, C++</dd><dt>Libraries & tools</dt><dd>PyTorch, NumPy, pandas, Matplotlib, LangChain, Docker, Git, LaTeX</dd><dt>Machine learning</dt><dd>Neural network architectures, model training, evaluation, experimental design</dd><dt>LLMs & agents</dt><dd>Tool use, retrieval-augmented generation, multi-agent systems, agent evaluation, repository automation</dd></dl></section><section class="cv-section" id="courses"><h2>Relevant coursework</h2><h3>Mathematics</h3><p>Mathematical Analysis, Linear Algebra, Numerical Analysis, Probability and Statistics, Discrete Mathematics</p><h3>Computer science</h3><p>Data Structures, Algorithm Design and Analysis, C++ Programming, Machine Learning, Deep Learning, Reinforcement Learning, Introduction to Intelligent Robotics, Computer Architecture</p></section></div></div>`;
const credits = `<section class="page-intro container"><span class="section-tag">Attribution</span><h1>Sources &amp; credits</h1><p>Personal information is supplied by Zihang Zhou. Paper metadata and original figures were checked against the following arXiv versions on September 18, 2026.</p></section><section class="container prose section-tight"><h2>Publication figures</h2>${papers.map(p=>`<article><h3>${esc(p.short)}</h3><p>${p.authors.map(esc).join(', ')}. <em>${esc(p.title)}</em>, ${p.year}.</p><p>${esc(p.figure)}. ${link('https://arxiv.org/html/'+p.version,'Versioned paper')} · ${link(p.source,'Original image')}. Used without substantive modification; scaled to fit the page.</p><p>Rights: ${esc(p.license)}${p.license==='CC BY 4.0'?' · <a href="https://creativecommons.org/licenses/by/4.0/">License terms</a>':''}</p></article>`).join('')}<h2>Publication status</h2><p>EMNLP 2026 Main Conference (Oral), the NeurIPS 2026 submissions, and the IEEE TKDE submission are reported by the author. These statuses were not independently established by the checked arXiv abstract pages. An under-review manuscript is not presented as an accepted paper.</p><h2>Design &amp; assets</h2><p>Layout, color tokens, alternating project rows, and motion patterns are adapted from ${link('https://github.com/xiyuanyang-code/whoami/tree/3fda181e1ebd679e32a06ed0105715f96fddca30','Xiyuan Yang’s Who Am I portfolio')} (copyright 2025 Xiyuan Yang), under the ${link('./whoami-LICENSE.txt','MIT License')}. The adaptation adds publication details, a CV, keyboard-accessible figure viewing, dark mode, and reduced-motion support. His personal text and project images are not reused. Paper images are credited above. No visitor tracking or third-party analytics are embedded.</p><h2>Maintenance</h2><p>The site and downloadable CV were last updated in September 2026. For corrections, ${link('mailto:zzh2024@sjtu.edu.cn','contact Zihang')}.</p></section>`;

for (const [route,title,content] of [['/','Home',home],['/publications/','Publications',publications],['/projects/','Projects',projects],['/cv/','CV',cv],['/credits/','Sources & credits',credits]]) {
  const dir = path.join(root, route.slice(1)); mkdirSync(dir,{recursive:true}); writeFileSync(path.join(dir,'index.html'),shell(title,route,content));
}
writeFileSync(path.join(root,'.nojekyll'),'');
writeFileSync(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/publications/','/projects/','/cv/','/credits/'].map(r=>`<url><loc>${base}${r}</loc></url>`).join('')}</urlset>`);
writeFileSync(path.join(root,'404.html'),shell('Page not found','/','<section class="page-intro container"><span class="eyebrow">404</span><h1>A small detour.</h1><p>This page could not be found.</p><a class="button primary" href="/">Back to home</a></section>').replaceAll('href="./','href="/').replaceAll('src="./','src="/'));
console.log('Generated 5 pages, 404, sitemap, robots, and .nojekyll.');